# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(356, 436)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QFrame{\n"
"background-color: rgb(211, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_adicionar = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_adicionar.setFont(font)
        self.bt_adicionar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.bt_adicionar.setObjectName("bt_adicionar")
        self.horizontalLayout.addWidget(self.bt_adicionar)
        self.input_site = QtWidgets.QLineEdit(Form)
        self.input_site.setObjectName("input_site")
        self.horizontalLayout.addWidget(self.input_site)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.bt_bloquear = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_bloquear.setFont(font)
        self.bt_bloquear.setStyleSheet("QPushButton{\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.bt_bloquear.setObjectName("bt_bloquear")
        self.verticalLayout.addWidget(self.bt_bloquear)
        self.bt_desbloquear = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_desbloquear.setFont(font)
        self.bt_desbloquear.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.bt_desbloquear.setObjectName("bt_desbloquear")
        self.verticalLayout.addWidget(self.bt_desbloquear)
        self.bt_excluir = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_excluir.setFont(font)
        self.bt_excluir.setStyleSheet("QPushButton{\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.bt_excluir.setObjectName("bt_excluir")
        self.verticalLayout.addWidget(self.bt_excluir)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        self.verticalLayout_2.addWidget(self.treeWidget)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Bloqueador de Sites"))
        self.bt_adicionar.setText(_translate("Form", "Adicionar"))
        self.bt_bloquear.setText(_translate("Form", "Bloquear"))
        self.bt_desbloquear.setText(_translate("Form", "Desbloquear"))
        self.bt_excluir.setText(_translate("Form", "Excluir"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "URL"))
